version: "3.7"

services:
  php:
    image: ciriacorafael/php:8-apache
    container_name: meuphp
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links: 
      - db

  db:
    image: mysql:5.7
    container_name: meudb
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - ./db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root